export const macrosGen = [
    {title: "Subject", text: "Su consulta sobre xxxtemaxxx del xxxfechaxxx del 2020 (xxxcasexxx)"},
    {title: "Opener (Female)", text: "Estimada Sra. xxxapellidoxxx,\n\nGracias por contactar a Porsche.\n\nEn referencia a su consulta del día xxxfechaxxx, "},
    {title: "Opener (Male)", text: "Estimado Sr. xxxapellidoxxx,\n\nGracias por contactar a Porsche.\n\nEn referencia a su consulta del día xxxfechaxxx,\n"},
    {title: "Delayed response", text: "Por favor acepte nuestras más sinceras disculpas por la demora en la respuesta. Le estamos agradecidos por su paciencia y lamentamos las posibles molestias causadas.\n"},
    {title: "Closer", text: "En caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Empathy - Services", text: "Siento mucho que su servicio xxxservicioxxx no esté funcionando correctamente. "},
    {title: "Empathy - Solution", text: "Estamos aquí para ayudarlo a encontrar una solución para su situación.\n"},
    {title: "Empathy - Utilize", text: "Siento mucho que no pueda utilizar xxxutilixxx"},
    {title: "Goodwill request (full)", text:"xxxopenerxxx nos gustaría informarle de que hemos enviado su solicitud de xxxreembxxxcompensxxx al departamento responsable.\nNuestros compañeros revisarán el caso y tan pronto el pedido sea procesado será notificado por correo electrónico y en su portal My Porsche.\n\nLamentamos los inconvenientes ocasionados y agradecemos su comprensión y paciencia en este asunto.\n\nEn caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Pairing code available (full)", text:"xxxopenerxxx nos gustaría informarle de que el código de emparejamiento ya se encuentra disponible en su cuenta My Porsche y en la aplicación Porsche Connect.Utilice este código para conectar la pantalla táctil de su vehículo (PCM) con la aplicación Porsche Connect.\n\nLamentamos los inconvenientes ocasionados y agradecemos su comprensión y paciencia en este asunto.\n\nEn caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Purchase & Invoice (full)", text: "xxxopenerxxx pudimos verificar que su compra se realizó correctamente y que los servicios están activos.\n\nPuede ver y descargar sus facturas en My Porsche > Mis pedidos.\n\nComo nota para uso futuro, tiene la opción de editar su información de facturación antes de completar cualquier compra.\n\nEn caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Missing information (full)", text: "xxxopenerxxx para que le podamos dar más asistencia en este caso, necesitaremos que nos proporcione la siguiente información:\n\n- Porsche ID (correo electrónico asociado a la cuenta) \n- Primer y último nombre.\n\nEn caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Ask screenshots (full)", text: "xxxopenerxxx nos gustaría pedirle disculpas por ls molestiaas causadas.\n\n Para que nuestro departamento técnico pueda atender su solicitud, por favor envíenos las capturas de pantalla, en donde se pueda ver la hora y el mensaje de error si es posible, además de las siguientes informaciones:\n\n - Versión de la App. \n- Sistema (IOS, Android …)\n - URL (SOLO em caso de ordenador)\n\nEnviaremos la información a nuestros compañeros y le informaremos acerca del estado del proceso.\nGracias por su comprensión y cooperación.\n\nSu equipo Porsche.\nSaludos cordiales.\n"},
    {title: "Case with support (full)", text: "xxxopenerxxx hemos informado de esta situación a nuestro departamento técnico. Nuestros compañeros lo están atendiendo. Tan pronto como tengamos información al respecto, le informaremos de inmediato.\n\nGracias por su paciencia y comprensión en este asunto.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Car Connect issue (full)", text: "Los servicios de Porsche Car Connect son prestados por Vodafone Automotive Telematics.\n\nLe pedimos para que por favor contacte directamente con Vodafone Automotive Telematics a través de los siguientes datos de contacto:\n\nTel: xxxtelefonoxxx\nCorreo electrónico: xxxcorreoxxx\nHorario de apertura: xxxhorarioxxx\n\nLe agradecemos su comprensión.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Support solved issue (full)", text: "xxxopenerxxx le debemos informar que nuestro departamento técnico ya nos ha informado de que se ha solucionado su situación. Le pedimos amablemente que nos confirme si de su lado todo está funcionando con normalidad.\n\nLe agradecemos su comprensión y en el caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"}
];

export const macrosPoo = [
    {title: "Subject", text: "Su pedido de registro de vehículo del xxxfechaxxx (xxxcasexxx)"},
    {title: "Opener (Female)", text: "Estimada Sra. xxxapellidoxxx,\n\nGracias por su interés Porsche.\n\n"},
    {title: "Opener (Male)", text: "Estimado Sr. xxxapellidoxxx,\n\nGracias por su interés Porsche.\n\n"},
    {title: "Rejected: Docs (full)", text: "xxxopenerxxx\nUsted nos contactó el día xxxfechaxxx solicitando el registro de su vehículo en su cuenta My Porsche. Para que podamos completarlo con éxito, quisiéramos pedirle que nos enviase los siguientes documentos:\n\nXXXDOCUMENTOSXXX\n \nPara proteger su información personal, cargue el documento a través del formulario de registro [https://connect-portal.porsche.com/core/es/es_ES/vehicles/add] ya que esto asegurará la transmisión encriptada. \n\nTan pronto como sus documentos estén completos y su activación para My Porsche se haya completado con éxito, se lo informaremos inmediatamente por correo electrónico. Si tiene cualquier otra duda o consulta, por favor no dude en contactarnos. \n \nSaludos cordiales, \nSu equipo Porsche.\n"},
    {title: "Rejected: Info (full)", text: "xxxopenerxxx\nUsted nos contactó el día xxxfechaxxx solicitando el registro de su vehículo en su cuenta My Porsche. Para que podamos completarlo con éxito, quisiéramos pedirle que responda a este correo electrónico con la siguiente información:\n\nXXXINFORMACIONXXX\n\nTan pronto como esta información adicional sea procesada y su activación para My Porsche se haya completado con éxito, se lo informaremos inmediatamente por correo electrónico. Si tiene cualquier otra duda o consulta, por favor no dude en contactarnos. \n \nSaludos cordiales, \nSu equipo Porsche.\n"},
    {title: "Rejected: Docs + Info (full)", text: "xxxopenerxxx\nUsted nos contactó el día xxxfechaxxx solicitando el registro de su vehículo en su cuenta My Porsche. Para que podamos completarlo con éxito, quisiéramos pedirle que enviase los siguientes documentos:\n\nXXXDOCUMENTOSXXX\n\nPara proteger su información personal, cargue el documento a través del formulario de registro [https://connect-portal.porsche.com/core/es/es_ES/vehicles/add] ya que esto asegurará la transmisión encriptada. \n\nQuisiéramos pedirle también que responda a este correo electrónico con la siguiente información:\n\nXXXINFORMACIONXXX\n\nTan pronto como estos datos sean procesados y su activación para My Porsche se haya completado con éxito, se lo informaremos inmediatamente por correo electrónico. Si tiene cualquier otra duda o consulta, por favor no dude en contactarnos.\n\nSaludos cordiales, \nSu equipo Porsche."},
    {title: "Denied: Not owner (full)", text: "xxxopenerxxx\nUsted nos contactó el día xxxfechaxxx solicitando el registro de su vehículo en su cuenta My Porsche. Sin embargo no fue posible completar el proceso por las siguientes razones:\n\n1. El pedido debe ser sometido desde la cuenta del propietario registrado del vehículo.\n\n2. Los datos en el formulario deben coincidir con la documentación enviada.\n\nSi la información de propietad no está actualizada, le rogamos que actualize la documentación antes de realizar nuevo pedido y en el caso de que no sea titular del vehículo, se podrá registrar como usuario secundario mediante una invitación enviada desde la cuenta de My Porsche del usuario principal.\n\nEn caso de que tenga alguna futura consulta, no dude en ponerse en contacto con nosotros.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "Proof of Identity", text: "#. Documento de identidad: El lado anverso del DNI del conductor que se identifica en el formulario, con todos los datos en el mismo visibles.\n"},
    {title: "Proof of Ownership", text: "#. Permiso de Circulación: El documento debe tener visible el VIN (número de bastidor) y el nombre del propietario. Si usted no es el propietario, por favor adjunte una autorización de la entidad propietaria del vehículo.\n"},
    {title: "Proof of Authorization", text: "#. Documento de autorización: Si el vehículo está en nombre de empresa, necesitamos un documento que autorice al conductor que se identifica en este proceso. Debe contener el VIN del vehículo, nombre y apellido del conductor, nombre de la empresa y las firmas de ambas partes.\n"},
    {title: "Activity: PoO for VIN", text: "INNSO xxxinnsoxxx\nPoO for VIN: xxxvinxxx\n\nMarket BP: xxxbpxxx > PC xxxpcxxx\n\nID:\n-First Name:\n-Last Name:\n-Date of Birth:\n-Validity:\n-ID Number:\n\nVehicle:\n-VIN:\n-First Name:\n-Last Name:\n-Address: \n-Registration Date:\n\nVehicle Status: (New/CPO/Used/Private market) and why?\n>\n\nAuthorization:\n-Company Name:\n-Signed by:\n-VIN:\n-Auth. Driver First Name:\n-Auth. Driver Last Name:\n\nForm:\n-First Name:\n-Last Name:\n-Porsche ID:\n-Mobile:\n-Address:\n-Dealer ID:\n\n\nNotes: \n#-->: [xxxnamexxx] xxxdatexxx:\n"},
    {title: "Activity: VIN already linked to BP", text: "INNSO xxxinnsoxxx\nVIN already linked to BP.\n\nMarket BP: xxxbpxxx > PC xxxpcxxx\n\nForm:\n-First Name:\n-Last Name:\n-Porsche ID:\n-Mobile:\n-Dealer ID: \n\n#-->: [xxxnamexxx] xxxdatexxx:\n"},
    {title: "PC notification: Description", text: "Smart Mobility - Nuevo Proprietario"},
    {title: "PC notification: Notes (BP + VIN)", text: "Estimado Centro Porsche,\n\nSe ha registrado un nuevo cliente a través del Portal My Porsche para su concesión.\n\nNº de BP : xxxbpxxx\nNº VIN: xxxvinxxx\n \nLe rogamos que realice las siguientes tareas:\n  1. Asignar un comercial y asesor responsable.\n  2. Revisar los datos del cliente en C@P.\n  3. Contactar con el cliente para darle la bienvenida a su Centro Porsche y presentarle su asesor/comercial responsable.\n\nEn el portal My Porsche el cliente ha aceptado ser contactado por su Centro Porsche inicialmente por correo postal o correo electrónico.\n \nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "PC notification: Notes (VIN only)", text: "Estimado Centro Porsche,\n\nUn cliente de su concesión ha registrado su vehículo a través del portal My Porsche. Hemos creado la relación con el vehículo después de comprobar los documentos presentados.\n\nNº de BP : xxxbpxxx\nNº VIN: xxxvinxxx\n\nLe rogamos que realice las siguientes tareas:\n\n  1. Asignar un comercial y asesor responsable\n  2. Revisar los datos del cliente en C@P\n  3. Contactar con el cliente para darle la bienvenida a su Centro Porsche y presentarle su asesor /comercial responsable (si necesario).\n\nEn el portal My Porsche el cliente ha aceptado ser contactado por su Centro Porsche inicialmente por correo postal o correo electrónico.\n\nSaludos cordiales,\nSu equipo Porsche.\n"},
    {title: "PC notification: CRM Managers", text: "ppn.porsche.com/portal/docs/DOC-123296"}
];

export const macrosPpn = [
    {title: "Missing information", text: "https://ppn.porsche.com/portal/docs/DOC-128901"},
    {title: "Frist reminder", text: "https://ppn.porsche.com/portal/docs/DOC-146910"},
    {title: "Second reminder", text: "https://ppn.porsche.com/portal/docs/DOC-146932"},
    {title: "Non-European market", text: "https://ppn.porsche.com/portal/docs/DOC-320813"}
]